module.exports.queries = ["SELECT * FROM employee WHERE role='manager' ORDER BY empl_surname;",
"SELECT * FROM product WHERE category_number=%PAR%;",
"SELECT phone_number, city, street, zip_code FROM employee WHERE empl_surname=%PAR%;",
"SELECT * FROM product ORDER BY product_name;",
"SELECT * FROM category ORDER BY category_name;",
"SELECT * FROM product WHERE category_number=%PAR%;",
"SELECT * FROM store_product WHERE id_product=%PAR%;",
"SELECT selling_price, products_number FROM store_product WHERE UPC=%PAR%;",
"SELECT * FROM store_product WHERE promotional_product=TRUE ORDER BY products_number;",
"SELECT UPC, UPC_prom, store_product.id_product, selling_price, products_number, promotional_product FROM store_product INNER JOIN product ON store_product.id_product = product.id_product WHERE promotional_product=TRUE ORDER BY product.product_name;",
"SELECT * FROM store_product WHERE promotional_product=FALSE ORDER BY products_number;",
"SELECT UPC, UPC_prom, store_product.id_product, selling_price, products_number, promotional_product FROM store_product INNER JOIN product ON store_product.id_product = product.id_product WHERE promotional_product=FALSE ORDER BY product.product_name;",
"SELECT * FROM `check` WHERE id_employee=%PAR1% AND (print_date BETWEEN %PAR2% AND %PAR3%);",
"SELECT * FROM `check` WHERE (print_date BETWEEN %PAR1% AND %PAR2%);",
"SELECT SUM(sum_total) FROM `check` WHERE id_employee=%PAR1% AND (print_date BETWEEN %PAR2% AND %PAR3%);",
"SELECT SUM(sum_total) FROM `check` WHERE (print_date BETWEEN %PAR1% AND %PAR2%);",
"SELECT SUM(sale.products_number) FROM sale INNER JOIN `check` ON sale.check_number = `check`.check_number WHERE sale.UPC=%PAR1% AND (print_date BETWEEN %PAR2% AND %PAR3%);",
"SELECT cust_surname, cust_name, cust_patronymic, phone_number, city, street, zip_code FROM customer_card;",
"SELECT * FROM customer_card WHERE percent=%PAR1%;",
"SELECT selling_price, products_number, product_name, characteristics FROM store_product INNER JOIN product p on store_product.id_product = p.id_product WHERE UPC=%PAR1%;",

// MANAGER QUERIES
"SELECT * FROM `check` WHERE id_employee=%PAR1% AND (print_date BETWEEN %PAR2% AND %PAR3%);",
"SELECT * FROM `check` WHERE check_number=%PAR1%;",
"SELECT * FROM customer_card WHERE cust_surname=%PAR1%;",
"SELECT * FROM customer_card WHERE percent=%PAR1%;",
"SELECT * FROM product WHERE category_number=%PAR1% ORDER BY product_name;",
"SELECT * FROM product ORDER BY product_name;",
"SELECT UPC, UPC_prom, id_product, selling_price, products_number, promotional_product FROM store_product WHERE promotional_product=TRUE ORDER BY products_number;",
"SELECT UPC, UPC_prom, store_product.id_product, selling_price, products_number, promotional_product FROM store_product INNER JOIN product p on store_product.id_product = p.id_product WHERE promotional_product=TRUE ORDER BY product_name;",
"SELECT UPC, UPC_prom, id_product, selling_price, products_number, promotional_product FROM store_product WHERE promotional_product=FALSE ORDER BY products_number;",
"SELECT UPC, UPC_prom, store_product.id_product, selling_price, products_number, promotional_product FROM store_product INNER JOIN product p on store_product.id_product = p.id_product WHERE promotional_product=FALSE ORDER BY product_name;",
"SELECT store_product.UPC, UPC_prom, id_product, store_product.selling_price, store_product.products_number, promotional_product FROM store_product INNER JOIN sale s on store_product.UPC = s.UPC WHERE check_number=%PAR1%;",
"SELECT selling_price, products_number FROM store_product INNER JOIN product p on store_product.id_product = p.id_product WHERE UPC=%PAR1%;",
"SELECT id_employee, empl_surname, empl_name, empl_patronymic, role, salary, date_of_birth, date_of_start, phone_number, city, street, zip_code FROM employee WHERE id_employee=%PAR1%;",
];
